import Footer from "@/components/Footer"
import Header from "@/components/Header"
import { Metadata } from "next"

export const metadata: Metadata = {
  title: {
    default: "NextJS Tutotial | LOkesh",
    template: "%s | Lokesh"
  },
  description: 'Generated by Next.js',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body>
        <Header />
        {children}
        <Footer />
      </body>
    </html>
  )
}
